import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "../sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function AboutLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      <Sidebar />
      <div>{children}</div>
    </section>
  );
}
